# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testing_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #加背景顏色
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-80, -15, 1521, 881))
        self.label_3.setStyleSheet("background-color:#DCF1FE;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        
        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 830, 590))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet('''
            QTabWidget::pane {
                border-top: 2px solid #FFFFFF;
                border-left: 2px solid #FFFFFF;
                border-right: 2px solid #FFFFFF;
                border-bottom: 2px solid #FFFFFF;
                position: absolute;
                top: -0.5em;
            }

            QTabWidget::tab-bar {
                alignment: center;
            }

            QTabBar::tab {
                background: lightgray;
                border: 1px solid #000000;
                border-bottom-color: #FFFFFF;
                border-top-left-radius: 4px;
                border-top-right-radius: 4px;
                min-width: 8ex;
                padding: 5px;
                font: bold 14px 'Microsoft JhengHei';
            }

            QTabBar::tab:selected, QTabBar::tab:hover {
                background: #FFFFFF;
            }

            QTabBar::tab:selected {
                color: #000093;
                border-color: #000093;
            }

            QTabBar::tab:!selected {
                margin-top: 2px;
            }
        ''')
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(-5, 51, 831, 511))
        self.tableView.setStyleSheet('''
             QTableView {
                    selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0.8,
                    stop: 0 #000079, stop: 1 white);  
                    alternate-background-color: #F0F8FF;
                    
            }
            QHeaderView::section { 
                    background-color: #ACD6FF; 
                    color: black; }
        ''')
        self.tableView.verticalScrollBar().setStyleSheet("QScrollBar:vertical { background: #FFFFFF; }")
        self.tableView.horizontalScrollBar().setStyleSheet("QScrollBar:horizontal { background: #FFFFFF; }")
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 101, 31))
        self.pushButton.setStyleSheet('''
            QPushButton{
                font-family:Microsoft JhengHei;
                font-size:15px;
                background-color: #FFFFFF;
                border-style: outset;
                border: 2px solid #000093;
                border-radius: 10px;
                padding: 5px;}
            QPushButton:hover{
                background-color: lightblue;}
            QPushButton:pressed{
                background-color: darkblue;}
        ''')
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 681, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setRange(1, 10000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.pushButton_predict = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_predict.setGeometry(QtCore.QRect(710, 50, 111, 41))
        self.pushButton_predict.setStyleSheet('''
            QPushButton{
                font-family:Microsoft JhengHei;
                font-size:15px;
                background-color: #FFFFFF;
                border-style: outset;
                border: 2px solid #4CAF50;
                border-radius: 10px;
                padding: 5px;}
            QPushButton:hover{
                background-color: lightblue;}
            QPushButton:pressed{
                background-color: darkblue;}
        ''')
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 801, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 25))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuback = QtWidgets.QMenu(self.menubar)
        self.menuback.setObjectName("menuback")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName('actionBack')
        self.menufile.addAction(self.actionExport)
        self.menuback.addAction(self.actionBack)
        self.menubar.addAction(self.menuback.menuAction())
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "員工管理系統"))
        self.pushButton.setText(_translate("MainWindow", "離職預測"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "全體員工離職預測"))
        self.label.setText(_translate("MainWindow", "請輸入待預測的員工編號："))
        self.pushButton_predict.setText(_translate("MainWindow", "預測"))
        self.label_2.setText(_translate("MainWindow", "約談信內容編輯："))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">親愛的員工你好：</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我希望與您來一場深度的工作詳談，了解近期您在工作上是否遇到困難</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">希望您回覆此信件，告知方便的時間</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">謝謝您的合作，期待見面的時刻</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">謹致問候,</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你的老闆安安<br />辦公室878號<br />電話:4125252</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "個別離職預測"))
        self.menufile.setTitle(_translate("MainWindow", "檔案"))
        self.menuback.setTitle(_translate("MainWindow", "回上一頁"))
        self.actionExport.setText(_translate("MainWindow", "Data export"))
        self.actionBack.setText(_translate("MainWindow", "Back to Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
